### ISSUE TITLE
Preserve directory structure

### ISSUE THREAD

**Issue by famod** [davidmoten/plantuml-maven-plugin#22]
First off: nice plugin, especially since it has recent releases/is actively maintained!

Coming from the old `com.github.jeluard:plantuml-maven-plugin`, I'm missing the feature of preserving the source directory structure, e.g. `foo/bar.puml` and `baz/bing.puml` will end up (as png) in the output directory "flat" next to each other instead of `foo/bar.png` and `baz/bing.png`.

**Comment by davidmoten** [comment]
You bet, that should be an easy enhancement. I'll have a look in the next few days.

**Comment by davidmoten** [comment]
0.2 is on Maven Central now with the new option. Please try it out.

**Comment by famod** [comment]
Works as expected, thanks!
